import { SEARCH_PRODUCT } from "./types";

const initialState = {
    categories: [
        {uuid: 'category1', name: 'Верхняя одежда'},
        {uuid: 'category2', name: 'Обувь'},
        {uuid: 'category3', name: 'Джинсы'},
        {uuid: 'category4', name: 'Платья'},
        {uuid: 'category5', name: 'Офисная одежда'}
    ],
    products: [
        {id: 'product1', category: 'category1', title: 'Куртка зимняя', price: 1500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product2', category: 'category1', title: 'Куртка кожаная', price: 1500, description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product3', category: 'category2', title: 'Ботинки', price: 4800, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product4', category: 'category3', title: 'Джинсы женские', price: 2200, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product5', category: 'category3', title: 'Джинсы мужские', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product6', category: 'category4', title: 'Сарафан', price: 500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product7', category: 'category5', title: 'Костюм', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product8', category: 'category5', title: 'Брюки', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product9', category: 'category5', title: 'Пиджак', price: 3500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product10', category: 'category1', title: 'Шапка', price: 1300, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product11', category: 'category1', title: 'Перчатки', price: 1000, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product12', category: 'category2', title: 'Туфли', price: 2600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product13', category: 'category1', title: 'Шарф', price: 3600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product14', category: 'category1', title: 'Пуховик', price: 3600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product15', category: 'category1', title: 'Шапка меховая', price: 1600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product16', category: 'category1', title: 'Ветровка', price: 1600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product17', category: 'category4', title: 'Летнее платье', price: 1900, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product18', category: 'category4', title: 'Юбка и топ', price: 2000, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product19', category: 'category2', title: 'Сапоги', price: 2100, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product20', category: 'category2', title: 'Кроссовки', price: 2100, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'}
    ], 
    newProducts: [
        {id: 'product1', category: 'category1', title: 'Куртка зимняя', price: 1500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product2', category: 'category1', title: 'Куртка кожаная', price: 1500, description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product3', category: 'category2', title: 'Ботинки', price: 4800, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product4', category: 'category3', title: 'Джинсы женские', price: 2200, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product5', category: 'category3', title: 'Джинсы мужские', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product6', category: 'category4', title: 'Сарафан', price: 500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product7', category: 'category5', title: 'Костюм', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product8', category: 'category5', title: 'Брюки', price: 2500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product9', category: 'category5', title: 'Пиджак', price: 3500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product10', category: 'category1', title: 'Шапка', price: 1300, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product11', category: 'category1', title: 'Перчатки', price: 1600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product12', category: 'category2', title: 'Туфли', price: 2600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product13', category: 'category1', title: 'Шарф', price: 3600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product14', category: 'category1', title: 'Пуховик', price: 3600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product15', category: 'category1', title: 'Шапка меховая', price: 1000, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product16', category: 'category1', title: 'Ветровка', price: 1600, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product17', category: 'category4', title: 'Летнее платье', price: 1900, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product18', category: 'category4', title: 'Юбка и топ', price: 2000, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product19', category: 'category2', title: 'Сапоги', price: 2100, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'},
        {id: 'product20', category: 'category2', title: 'Кроссовки', price: 2100, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo dui, consectetur sit amet vehicula sit amet, luctus nec ipsum. Praesent et interdum sem, ut viverra nisl. Sed scelerisque libero sit amet nisl rhoncus, vitae condimentum lectus malesuada.'}
    ]
}

export const dataReducer = (state=initialState, action)=>{
    switch(action.type){
        case SEARCH_PRODUCT:
            console.log(state.products, action.value)
            if(action.value.length === 0){
                return {
                    ...state, 
                    newProducts: state.products 
                }
            }
            return {
                ...state, 
                newProducts: state.products.filter(item=>{return item.title.indexOf(action.value)>-1})
            }
        default:
            return state
    }
}